version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    container_name: test-docker
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=node-docker
    ports:
      - 5434:5432